#development:
#  sessions:
#    default:
#      database: image
#      hosts:
#        - localhost:27017
#
#test:
#  sessions:
#    default:
#      database: image
#      hosts:
#        - localhost:27017
#
#production:
#  sessions:
#    default:
#      uri: <%= ENV["ECHO_URI"] %>

development:
  host: 127.0.0.1
  port: 27017
  database: gridfs_upload
production:
  host: 127.0.0.1
  port: 27017
  database: gridfs_upload
environment: development
