production:
sessions:
  default:
    hosts:
      - localhost:27017
    database: mongoid
    username: user
    password: password
  replica_set:
    hosts:
- dedicated1.myapp.com:27017
- dedicated2.myapp.com:27017
- dedicated3.myapp.com:27017
database: mongoid
options:
consistency: :eventual
safe: true
shard:
hosts:
- mongos.myapp.com:27017
database: mongoid
another:
uri: mongodb://user:pass@59.1.22.1:27017,59.1.22.2:27017/mongoid
options:
allow_dynamic_fields: false
identity_map_enabled: true
include_root_in_json: true
include_type_for_serialization: true
preload_models:
- Canvas
- Browser
- Firefox
scope_overwrite_exception: true
raise_not_found_error: false
skip_version_check: false
use_activesupport_time_zone: false
use_utc: true
